# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('no_node', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.DecisionNode')),
                ('yes_node', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.DecisionNode')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('initial_node', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DecisionNode')),
            ],
        ),
    ]
